---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  deploy-aur:
    # needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: Freed-Wu/update-aur-package@v1.0.11
        with:
          package_name: tmux-rime
          ssh_private_key: ${{secrets.AUR_SSH_PRIVATE_KEY}}

  deploy-ppa:
    # needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          path: tmux-rime-${{github.ref_name}}
      - uses: actions/checkout@v4
        with:
          repository: xmake-io/xmake-repo
          path: tmux-rime-${{github.ref_name}}/.xmake/repositories/xmake-repo
      - name: Build
        run: |
          tar vcafC ../tmux-rime-${{github.ref_name}}.tar.gz \
            tmux-rime-${{github.ref_name}} ..
      - uses: yuezk/publish-ppa-package@main
        with:
          repository: freedwu/rime
          extra_ppa: xmake-io/xmake
          gpg_private_key: ${{secrets.GPG_PRIVATE_KEY}}
          gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
          tarball: ../*.tar.*
          deb_email: ${{secrets.DEB_EMAIL}}
          deb_fullname: freedwu
